# This is a basic workflow to help you get started with Actions

name: sourcemod-package-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Install linux package
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update 
          sudo apt install -y clang g++-multilib lib32stdc++-7-dev lib32z1-dev libc6-dev-i386 linux-libc-dev:i386 curl git python3 python3-pip python3-setuptools python-setuptools automake cmake libtool

      - name: 'Prepare Sourcemod Repository'
        run: |
          git clone --recursive https://gitlab.com/counterstrikesource/sourcemod.git
          bash sourcemod/tools/checkout-deps.sh
          mkdir -p sourcemod/build

      - name: 'Compile Sourcemod'
        run: |
          cd sourcemod/build
          python3 ../configure.py --enable-optimize --enable-asan --sdks=csgo,css
          CLANG_DEFAULT_CXX_STDLIB=libc++ /home/github/.local/bin/ambuild
          tar cfvz sourcemod-1.11-nide.tar.gz package/

      - name: 'Upload Sourcemod'
        uses: actions/upload-artifact@v2
        with:
          name: sourcemod-package
          path: sourcemod/build/sourcemod-1.11-nide.tar.gz 
